name       : srt
version    : 1.4.2
release    : 1
source     :
    - https://github.com/Haivision/srt/archive/v1.4.2.tar.gz : 28a308e72dcbb50eb2f61b50cc4c393c413300333788f3a8159643536684a0c4
license    : MPL-2.0
component  : multimedia.library
homepage   : https://www.srtalliance.org/
summary    : Secure, Reliable, Transport
description: |
    Secure Reliable Transport (SRT) is an open source transport technology that optimizes streaming performance across unpredictable networks, such as the Internet.
setup      : |
    %cmake_ninja \
        -DENABLE_APPS=OFF \
        -DENABLE_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
