name       : srt
version    : 1.4.4
release    : 4
source     :
    - https://github.com/Haivision/srt/archive/refs/tags/v1.4.4.tar.gz : 93f5f3715bd5bd522b8d65fc0d086ef2ad49db6a41ad2d7b35df2e8bd7094114
license    : MPL-2.0
component  : multimedia.library
homepage   : https://www.srtalliance.org/
summary    : Secure, Reliable, Transport
description: |
    Secure Reliable Transport (SRT) is an open source transport technology that optimizes streaming performance across unpredictable networks, such as the Internet.
setup      : |
    %cmake_ninja \
        -DENABLE_APPS=OFF \
        -DENABLE_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
