name       : srt
version    : 1.4.3
release    : 2
source     :
    - https://github.com/Haivision/srt/archive/refs/tags/v1.4.3.tar.gz : c06e05664c71d635c37207a2b5a444f2c4a95950a3548402b3e0c524f735b33d
license    : MPL-2.0
component  : multimedia.library
homepage   : https://www.srtalliance.org/
summary    : Secure, Reliable, Transport
description: |
    Secure Reliable Transport (SRT) is an open source transport technology that optimizes streaming performance across unpredictable networks, such as the Internet.
setup      : |
    %cmake_ninja \
        -DENABLE_APPS=OFF \
        -DENABLE_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
